"""Single source of truth for the stock universe.
Imported by both data_ingestion.py and fetch_prices.py.
"""

NIFTY_50 = [
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS","HINDUNILVR.NS",
    "BHARTIARTL.NS","ITC.NS","SBIN.NS","LT.NS","BAJFINANCE.NS","MARUTI.NS",
    "HCLTECH.NS","AXISBANK.NS","TATAMOTORS.NS","SUNPHARMA.NS","WIPRO.NS","TITAN.NS",
    "NTPC.NS","POWERGRID.NS","KOTAKBANK.NS","ASIANPAINT.NS","ADANIPORTS.NS",
    "ULTRACEMCO.NS","NESTLEIND.NS","TECHM.NS","TATASTEEL.NS","JSWSTEEL.NS",
    "HINDALCO.NS","DIVISLAB.NS","DRREDDY.NS","CIPLA.NS","APOLLOHOSP.NS",
    "EICHERMOT.NS","BAJAJ-AUTO.NS","HEROMOTOCO.NS","M&M.NS","BPCL.NS","ONGC.NS",
    "COALINDIA.NS","GRASIM.NS","INDUSINDBK.NS","TATACONSUM.NS","BRITANNIA.NS",
    "HDFCLIFE.NS","SBILIFE.NS","BAJAJFINSV.NS","ADANIENT.NS","ZOMATO.NS","VEDL.NS",
]

NIFTY_NEXT_50 = [
    "SHRIRAMFIN.NS","HAVELLS.NS","PIDILITIND.NS","GODREJCP.NS","DABUR.NS",
    "AMBUJACEM.NS","ACC.NS","BANDHANBNK.NS","COLPAL.NS","NAUKRI.NS","MUTHOOTFIN.NS",
    "BERGEPAINT.NS","JUBLFOOD.NS","LUPIN.NS","BIOCON.NS","TVSMOTOR.NS","PAGEIND.NS",
    "AUROPHARMA.NS","ALKEM.NS","TORNTPHARM.NS","BALKRISIND.NS","MFSL.NS","CANBK.NS",
    "PNB.NS","BANKBARODA.NS","IDFCFIRSTB.NS","FEDERALBNK.NS","SAIL.NS",
    "NATIONALUM.NS","NMDC.NS","PETRONET.NS","IOC.NS","GAIL.NS","IRCTC.NS",
    "TRENT.NS","DMART.NS","PIIND.NS","SIEMENS.NS","ABB.NS","HAL.NS","BEL.NS",
    "BHEL.NS","CONCOR.NS","IRFC.NS","PFC.NS","RECLTD.NS","NHPC.NS","SJVN.NS",
    "POLYCAB.NS","VOLTAS.NS",
]

NIFTY_MIDCAP_150 = [
    "CHOLAFIN.NS","BAJAJHLDNG.NS","AUBANK.NS","RBLBANK.NS","SBICARD.NS",
    "KARURVYSYA.NS","CITYUNIONBK.NS","MAHABANK.NS","EQUITASBNK.NS","CREDITACC.NS",
    "UJJIVANSFB.NS","ICICIPRULI.NS","ICICIGI.NS","STARHEALTH.NS","NIACL.NS",
    "GICRE.NS","MANAPPURAM.NS","ANGELONE.NS","MOTILALOFS.NS","360ONE.NS",
    "JMFINANCIL.NS","CDSL.NS","BSE.NS","MCX.NS","CAMS.NS","KFINTECH.NS",
    "MPHASIS.NS","PERSISTENT.NS","COFORGE.NS","LTTS.NS","KPITTECH.NS",
    "TATAELXSI.NS","TANLA.NS","MASTEK.NS","ZENSAR.NS","AFFLE.NS","INDIAMART.NS",
    "RATEGAIN.NS","LATENTVIEW.NS","HAPPSTMNDS.NS","TATACOMM.NS","ROUTE.NS",
    "EMAMILTD.NS","RADICO.NS","VSTIND.NS","UNITEDBREW.NS","UNITEDSPIRITS.NS",
    "GODREJIND.NS","MARICO.NS","JYOTHYLAB.NS","ZYDUSWELL.NS","SUNDRMFAST.NS",
    "MOTHERSON.NS","ENDURANCE.NS","ESCORTS.NS","TIINDIA.NS","BHARATFORG.NS",
    "APOLLOTYRE.NS","CEAT.NS","BOSCHLTD.NS","CRAFTSMAN.NS","THERMAX.NS",
    "CUMMINSIND.NS","AIAENG.NS","ELGIEQUIP.NS","TIMKEN.NS","SCHAEFFLER.NS",
    "SKF.NS","GRINDWELL.NS","PRAJ.NS","RVNL.NS","RAILTEL.NS","GODREJPROP.NS",
    "SOBHA.NS","PRESTIGE.NS","BRIGADE.NS","PHOENIXLTD.NS","OBEROIRLTY.NS",
    "ASTRAL.NS","SUPREMEIND.NS","CERA.NS","KAJARIA.NS","RAMCOCEM.NS","JKCEMENT.NS",
    "DALMIACBT.NS","CENTURYPLY.NS","DEEPAKFERT.NS","COROMANDEL.NS","ATUL.NS",
    "NAVINFLUOR.NS","VINATI.NS","DEEPAKNTR.NS","AARTIIND.NS","FINEORG.NS",
    "CLEAN.NS","TATACHEM.NS","TORNTPOWER.NS","IGL.NS","MGL.NS","GUJGASLTD.NS",
    "ATGL.NS","CESC.NS","JSWENERGY.NS","ADANIPOWER.NS","TATAPOWER.NS",
    "ADANIGREEN.NS","RATNAMANI.NS","HINDZINC.NS","MOIL.NS","CROMPTON.NS",
    "BLUESTARCO.NS","DIXON.NS","AMBER.NS","VGUARD.NS","MAXHEALTH.NS","FORTIS.NS",
    "METROPOLIS.NS","SYNGENE.NS","IPCA.NS","GLENMARK.NS","LAURUS.NS","ZYDUSLIFE.NS",
    "POLICYBZR.NS","PAYTM.NS","NYKAA.NS","DELHIVERY.NS","MAPMYINDIA.NS",
]

NIFTY_SMALLCAP_250 = [
    "AAVAS.NS","HOMEFIRST.NS","APTUS.NS","HUDCO.NS","IREDA.NS","NUVAMA.NS",
    "INTELLECT.NS","CYIENT.NS","KRBL.NS","LTFOODS.NS","BALRAMCHIN.NS",
    "AVANTIFEED.NS","KPRMILL.NS","SAREGAMA.NS","RAYMOND.NS","TRIDENT.NS",
    "WELSPUNLIV.NS","TEAMLEASE.NS","QUESS.NS","THYROCARE.NS","PFIZER.NS",
    "ABBOTINDIA.NS","GLAXO.NS","SANSERA.NS","GABRIEL.NS","JKTYRES.NS",
    "KEC.NS","APARINDS.NS","KEI.NS","PCBL.NS","GALAXYSURF.NS","ROSSARI.NS",
    "ALKYLAMINE.NS","NOCIL.NS","NETWORK18.NS","HFCL.NS","MOLDTKPAC.NS",
    "APLAPOLLO.NS","INOXWIND.NS","SUZLON.NS","DHANUKA.NS","RALLIS.NS",
    "RITES.NS","IRCON.NS","NBCC.NS","PVRINOX.NS","LALPATHLAB.NS",
]

US_STOCKS = [
    "AAPL","MSFT","GOOGL","AMZN","NVDA","META","TSLA","AVGO","ORCL","ADBE",
    "CRM","AMD","INTC","QCOM","TXN","IBM","NOW","WDAY","PANW","CRWD","ZS",
    "DDOG","NET","SNOW","PLTR","NFLX","V","MA","PYPL","JPM","BAC","GS","MS",
    "BLK","UNH","JNJ","LLY","PFE","ABBV","MRK","AMGN","MDT","ABT","TMO",
    "WMT","PG","KO","PEP","COST","HD","NKE","MCD","SBUX","XOM","CVX","COP",
    "HON","CAT","BA","GE","DE","UPS","LMT","RTX","T","VZ","DIS","NEE","AMT",
    "F","GM","UBER","ABNB",
]

ALL_NSE_STOCKS = list(dict.fromkeys(
    NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP_150 + NIFTY_SMALLCAP_250
))

ALL_SYMBOLS = list(dict.fromkeys(ALL_NSE_STOCKS + US_STOCKS))
